### ISSUE TITLE
Get error:(

### ISSUE THREAD

**Issue by Esorat** [houtenbos/krakura-bot#13]
Error: The WASM interface has not been initialized. Ensure that you wait for the initialization Promise with waitReady() from @polkadot/wasm-crypto (or cryptoWaitReady() from @polkadot/util-crypto) before attempting to use WASM-only interfaces.
    at assert (C:\Users\Lissk\Desktop\krakura-bot\node_modules\@polkadot\util\assert.cjs:37:11)
    at C:\Users\Lissk\Desktop\krakura-bot\node_modules\@polkadot\util-crypto\node_modules\@polkadot\wasm-crypto\bridge.cjs:36:22
    at sr25519PairFromSeed (C:\Users\Lissk\Desktop\krakura-bot\node_modules\@polkadot\util-crypto\sr25519\pair\fromSeed.cjs:24:82)
    at Object.sr25519 (C:\Users\Lissk\Desktop\krakura-bot\node_modules\@polkadot\api\node_modules\@polkadot\keyring\keyring.cjs:24:56)
    at Keyring.createFromUri (C:\Users\Lissk\Desktop\krakura-bot\node_modules\@polkadot\api\node_modules\@polkadot\keyring\keyring.cjs:271:115)
    at Keyring.addFromUri (C:\Users\Lissk\Desktop\krakura-bot\node_modules\@polkadot\api\node_modules\@polkadot\keyring\keyring.cjs:188:30)
    at Keyring.addFromMnemonic (C:\Users\Lissk\Desktop\krakura-bot\node_modules\@polkadot\api\node_modules\@polkadot\keyring\keyring.cjs:148:17)
    at C:\Users\Lissk\Desktop\krakura-bot\build\connectors\karura\karura-client.js:36:37    
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.

**Comment by options2015** [comment]
I am getting the same error. Possible to look into this @houtenbos 

Thank you!
