### ISSUE TITLE
error value too small

### ISSUE THREAD

**Issue by k4m4h4l** [houtenbos/krakura-bot#9]
friend excuse me but i have 16 USD balance on kraken and i wanted to test the code, but the bot always gives this error "Order too small to place on kraken. Order size: 0, min order size: 0.02"

in the settings there is no minimum input value only maximum value

 which configuration should i put to test with the minimum value.

**Comment by k4m4h4l** [comment]
would you have a social network that we can talk to?

I am willing to make donations if I can run the code and earn additional income.

**Comment by houtenbos** [comment]
Do you have balance on Karura as well? 
You can find me on telegram at @LHBTS.

**Comment by k4m4h4l** [comment]
MongooseError: Operation `tickers.insertOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/home/ubuntu/krakura/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:149:23)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
MongooseError: Operation `tickers.insertOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/home/ubuntu/krakura/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:149:23)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
Buy 0.026745 KSM @ kraken for 303.78, sell @ karura for 305.70  - margin: 0.06999999999999999 %
Order too small to place on kraken. Order size: 0, min order size: 0.02
Buy 0.026745 KSM @ kraken for 303.83, sell @ karura for 305.70  - margin: 0.05 %
Order too small to place on kraken. Order size: 0, min order size: 0.02

**Comment by k4m4h4l** [comment]
i have 17 usd in kraken and 12 usd on karura

**Comment by k4m4h4l** [comment]
the bot worked bought the equivalent of 8 usd ksm on kraken and bought the equivalent of 8 usd on kusd on kurama. but it stopped there and now it only gives a mongose ​​error



MongooseError: Operation `balances.insertOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/home/ubuntu/krakura/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:149:23)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
MongooseError: Operation `balances.insertOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/home/ubuntu/krakura/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:149:23)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
MongooseError: Operation `tickers.insertOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/home/ubuntu/krakura/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:149:23)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
MongooseError: Operation `tickers.insertOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/home/ubuntu/krakura/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:149:23)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)

**Comment by matthewashley1** [comment]
You are seeing these MongooseErrors because we were working on integrating Mongdb for running the project from Docker and haven't completed all the changes yet. If you pull the loki branch and run from there you shouldn't see any more errors and should be able to continue trading. 

Thanks for your interest in the project, we are working on providing more functionality.

**Comment by k4m4h4l** [comment]
so friend i installed the loki version, and now i really didn't get any more mongo error, but now when i run yarn start i only have the answer:

Order too small to place on kraken. Order size: 0, min order size: 0.02
Order too small to place on kraken. Order size: 0, min order size: 0.02
Order too small to place on kraken. Order size: 0, min order size: 0.02
Order too small to place on kraken. Order size: 0, min order size: 0.02
Order too small to place on kraken. Order size: 0, min order size: 0.02
Order too small to place on kraken. Order size: 0, min order size: 0.02
Order too small to place on kraken. Order size: 0, min order size: 0.02
Order too small to place on kraken. Order size: 0, min order size: 0.02
Order too small to place on kraken. Order size: 0, min order size: 0.02
Order too small to place on kraken. Order size: 0, min order size: 0.02
Order too small to place on kraken. Order size: 0, min order size: 0.02
Order too small to place on kraken. Order size: 0, min order size: 0.02
Order too small to place on kraken. Order size: 0, min order size: 0.02
Order too small to place on kraken. Order size: 0, min order size: 0.02
Order too small to place on kraken. Order size: 0, min order size: 0.02
Order too small to place on kraken. Order size: 0, min order size: 0.02
Order too small to place on kraken. Order size: 0, min order size: 0.02


but y have funds in kraken and karura

**Comment by matthewashley1** [comment]
@k4m4h4l If you are seeing this repeated message, then that means you don't have enough USD in your balances to fill the minimum order requirements of Kraken.
